# Generated by Django 5.2 on 2025-05-03 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('apa', 'Apă'), ('curent', 'Curent'), ('gaze', 'Gaze')], max_length=10)),
                ('furnizor', models.CharField(max_length=100)),
                ('index_vechi', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('index_nou', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unitate_masura', models.CharField(max_length=10)),
                ('pret_unitar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
